WriterMvcProject/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using DataAccesLayer.EntitiyFramework;
using EntitiyLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
namespace WriterMvcProject.Controllers
{
    public class HeadingController : Controller
    {
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterManager wm = new WriterManager(new EfWriterDal());
        // GET: Heading
        public ActionResult Index(int p=1)
        {
            var Headingvalues = hm.GetList().ToPagedList(p,7);


            return View(Headingvalues);
        }

        public ActionResult HeadingReport()
        {
            var Headingvalues = hm.GetList();


            return View(Headingvalues);
        }

        [HttpGet]
        public ActionResult AddHeading()
        {
            List<SelectListItem> CategoryValues = (from x in cm.GetList()
                                                   select new SelectListItem
                                                   {
                                                       Text = x.CategoryName,
                                                       Value = x.CategoryID.ToString()
                                                   }).ToList();
            ViewBag.categoryvalues = CategoryValues;



            List<SelectListItem> writerlist = (from x in wm.GetList()
                                               select new SelectListItem
                                               {
                                                   Text = x.WriterName + " " + x.WriterSurname,
                                                   Value = x.WriterID.ToString()
                                               }
                                             ).ToList();
            ViewBag.writerlist = writerlist;


            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading p)
        {
            p.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.HeadingStatus = true;
            hm.HeadingAdd(p);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            var headingvalue = hm.GetByID(id);
            List<SelectListItem> Categorylist = (from x in cm.GetList() select new SelectListItem {Value=x.CategoryID.ToString(), Text=x.CategoryName
            }
            ).ToList();

            ViewBag.vlc = Categorylist;
            return View(headingvalue);
        }

        [HttpPost]
        public ActionResult EditHeading(Heading heading)


        {
            heading.HeadingStatus = true;
            hm.HeadingUpdate(heading);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteHeading(int id)
        {
            var value = hm.GetByID(id);
            value.HeadingStatus = false;
            hm.HeadingDelete(value);
            return RedirectToAction("Index");
        }

        public ActionResult PassiveHeading(int p=1)
        {
            var values = hm.GetListByHeadingStatus().ToPagedList(p,7);
            return View(values);
        }

        public ActionResult HeadingbyWriter(int id,int p=1)
        {
            var values = hm.GetListByWriter(id).ToPagedList(p,7);
            return View(values);
        }
    }
}

WriterMvcProject/Views/Heading/AddHeading.cshtml
@model EntitiyLayer.Concrete.Heading
@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Başlık Ekle</h2>


@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
<div class="form-group">

    @Html.Label("Başlık Adı")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.HeadingName)
    <br />

    @Html.Label("Kategori ID")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.categoryvalues, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CategoryID)
    <br />

    @Html.Label("Yazar ID")
    @Html.DropDownListFor(x=>x.WriterID,(List<SelectListItem>)ViewBag.writerlist, new {@class="form-control"})
    @Html.ValidationMessageFor(x => x.WriterID)
    <br />

    <button class="btn btn-outline-success">Kaydet</button>

</div>

}

WriterMvcProject/Views/Heading/EditHeading.cshtml
@model EntitiyLayer.Concrete.Heading
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Başlık Güncelleme Sayfası</h2>

@using (Html.BeginForm("EditHeading", "Heading", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Başlık ID")
    @Html.TextBoxFor(x => x.HeadingID, new { @class = "form-control" })

    <br />
    @Html.Label("Başlık Başlık Adı")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.HeadingDate, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
    <br />
    @Html.Label("Yazar ID")
    @Html.TextBoxFor(x => x.WriterID, new { @class = "form-control" })
    <br />

    <button type="submit" id="güncelleme" class="btn btn-outline-success">Güncelle</button>
</div>
    
}
@*<script src="~/Templates/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>*@

WriterMvcProject/Views/Heading/HeadingReport.cshtml
@using EntitiyLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "HeadingReport";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Yazar Sözlük Raporlama sayfası</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
</head>
<body>
    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
        <thead>
            <tr>
                <th>Başlık Id</th>
                <th>Başlık Adı</th>
                <th>Tarih</th>
                <th>Yazar</th>
                <th>Kategori</th>
                <th>Durum</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model)
            {
                <tr>
                    <td>@x.HeadingID</td>
                    <td>@x.HeadingName</td>
                    <td>@x.HeadingDate</td>
                    <td>@x.Writer.WriterName @x.Writer.WriterSurname</td>
                    <td>@x.Category.CategoryName</td>
                    <td>@x.HeadingStatus</td>

                </tr>
            }

        </tbody>
    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>

    <script>
        $(document).ready(function () {
            var table = $('#example').DataTable({
                lengthChange: false,
                buttons: [
                    {
                        extend: 'copy',
                        text: 'Kopyala' // Kopyala düğmesinin metni
                    },
                    {
                        extend: 'excel',
                        text: 'Excel İndir' // Excel düğmesinin metni
                    },
                    {
                        extend: 'csv',
                        text: 'CSV İndir' // CSV düğmesinin metni
                    },
                    {
                        extend: 'pdf',
                        text: 'PDF İndir' // PDF düğmesinin metni
                    },
                    {
                        extend: 'colvis',
                        text: 'Filtreleme' // Sütun görünürlüğü düğmesinin metni
                    }
                ],
                language: {
                    buttons: {
                        copyTitle: 'Panoya kopyalandı',
                        copySuccess: {
                            _: '%d satır kopyalandı',
                            1: '1 satır kopyalandı'
                        }
                    }
                }
            });

            table.buttons().container()
                .appendTo('#example_wrapper .col-md-6:eq(0)');
        });
    </script>




</body>
</html>

WriterMvcProject/Views/Heading/HeadingbyWriter.cshtml
@using EntitiyLayer.Concrete
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Heading>
@{
    ViewBag.Title = "HeadingbyWriter";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}


<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <!-- Navbar -->
    <!-- /.navbar -->
    <!-- Main Sidebar Container -->
    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <!--<section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Projects</h1>
                </div>
            </div>
        </div>-->
    <!-- /.container-fluid -->
    <!--</section>-->
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Aktif Başlıklar</h3>


                <div class="card-tools">


                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>


                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 5%">
                                Başlık Adı
                            </th>
                            <th style="width: 5%">
                                Oluşturma Tarihi

                            </th>
                            <th style="width: 5%" class="text-center">
                                Yazar Bilgisi
                            </th>

                            <th style="width: 5%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 10%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {


                            <tr>

                                <td>
                                    @item.HeadingID
                                </td>

                                <td>
                                    @item.HeadingName
                                </td>
                                <td>
                                    <a>

                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMMMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline" style="text-align:center;">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>

                                <td class="project-state">
                                    <span class="badge badge-success">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        Başlık Detayı
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Heading/EditHeading/@item.HeadingID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm silme" href="/Heading/DeleteHeading/@item.HeadingID">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>

                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- /.content -->
    <!-- /.content-wrapper -->
    @*////////////////////////**************Pasif Başlıklar************************************////////////////////*@

    <script src="~/Templates/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>  @*//Side bar için eklendi*@
</body>

</html>
@Html.PagedListPager((IPagedList)Model, p => Url.Action("Index", new { p }), new PagedListRenderOptions

{
LiElementClasses = new List<string>
{"page-link"}
})

WriterMvcProject/Views/Heading/Index.cshtml
@using EntitiyLayer.Concrete
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <!-- Navbar -->
    <!-- /.navbar -->
    <!-- Main Sidebar Container -->
    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <!--<section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Projects</h1>
                </div>
            </div>
        </div>-->
    <!-- /.container-fluid -->
    <!--</section>-->
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Aktif Başlıklar</h3>


                <div class="card-tools">


                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>


                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 5%">
                                Başlık Adı
                            </th>
                            <th style="width: 5%">
                                Oluşturma Tarihi

                            </th>
                            <th style="width: 5%" class="text-center">
                                Yazar Bilgisi
                            </th>

                            <th style="width: 5%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 10%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {


                            <tr>

                                <td>
                                    @item.HeadingID
                                </td>

                                <td>
                                    @item.HeadingName
                                </td>
                                <td>
                                    <a>

                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMMMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline" style="text-align:center;">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>

                                <td class="project-state">
                                    <span class="badge badge-success">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        Başlık Detayı
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Heading/EditHeading/@item.HeadingID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm silme" href="/Heading/DeleteHeading/@item.HeadingID">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>

                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- /.content -->
    <!-- /.content-wrapper -->
    @*////////////////////////**************Pasif Başlıklar************************************////////////////////*@

    <script src="~/Templates/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>  @*//Side bar için eklendi*@
</body>

</html>

<a href="/Heading/AddHeading/" class="btn btn-primary">Yeni Başlık Ekle </a>
<a href="/Heading/PassiveHeading/" class="btn btn-primary">Pasif Başlıkları Listele </a>

@Html.PagedListPager((IPagedList)Model, p => Url.Action("Index", new { p }), new PagedListRenderOptions

{
LiElementClasses = new List<string>
{"page-link"}
})

WriterMvcProject/Views/Heading/PassiveHeading.cshtml
@using EntitiyLayer.Concrete
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <!-- Navbar -->
    <!-- /.navbar -->
    <!-- Main Sidebar Container -->
    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <!--<section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Projects</h1>
                </div>
            </div>
        </div>-->
    <!-- /.container-fluid -->
    <!--</section>-->
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Pasif Başlıklar</h3>

                <div class="card-tools">


                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>


                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 5%">
                                Başlık Adı
                            </th>
                            <th style="width: 5%">
                                Oluşturma Tarihi

                            </th>
                            <th style="width: 5%" class="text-center">
                                Yazar Bilgisi
                            </th>

                            <th style="width: 5%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 10%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {


                            <tr>

                                <td>
                                    @item.HeadingID
                                </td>

                                <td>
                                    @item.HeadingName
                                </td>
                                <td>
                                    <a>

                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMMMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline" style="text-align:center;">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>

                                <td class="project-state">
                                    <span class="badge badge-success">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        Başlık Detayı
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Heading/EditHeading/@item.HeadingID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/Heading/DeleteHeading/@item.HeadingID">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>

                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- /.content -->
    <!-- /.content-wrapper -->
    @*////////////////////////**************Pasif Başlıklar************************************////////////////////*@
    <a href="/Heading/Index" class="btn btn-outline-secondary">Ana Sayfaya</a>

</body>


</html>
<script src="~/Templates/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
@Html.PagedListPager((IPagedList)Model, p => Url.Action("Index", new { p }), new PagedListRenderOptions

{
LiElementClasses = new List<string>
{"page-link"}
})