WriterMvcProject/Controllers/ContactController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccesLayer.EntitiyFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WriterMvcProject.Controllers
{
    public class ContactController : Controller
    {
        ContactManager contactManager = new ContactManager(new EfContactDal());
        ContactValidator cv = new ContactValidator();
        MessageManager mm = new MessageManager(new EfMessageDal());
        // GET: Contact
        public ActionResult Index(string search)
        {
           
           

            if (!string.IsNullOrEmpty(search))
            {
                var values = contactManager.GetListContactSearch(search);

                return View(values);
                   

            }
            else
            {
                var value = contactManager.GetList();
                return View(value);
            }
           
        }

        public ActionResult GetContactDetails(int id)
        {
            var values = contactManager.ContactGetByID(id);
            return View(values);
        }

        public PartialViewResult MessageListMenu()
        {
            string p = (string)Session["AdminUserName"];
            var count = mm.GetByCountSenderMessage(p);
            var recievercount = mm.GetByCountReceiverMessage(p);
            var garbagecount = mm.GetByCountGarbageMessage(p);

            int value = contactManager.GetContactCount();
            int valuetask = mm.GetByCountTaskMessage(p);
            ViewBag.contactcount = value;
            ViewBag.sendermailcount = count;
            ViewBag.receivercount = recievercount;
            ViewBag.garbagecount = garbagecount;
            ViewBag.Taskmessage = valuetask;
            return PartialView();
        }
    }
}

WriterMvcProject/Controllers/MessageController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccesLayer.EntitiyFramework;
using FluentValidation;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using System.Web.Services.Description;
using EntitiyLayer.Concrete;

namespace WriterMvcProject.Controllers
{
    public class MessageController : Controller
    {
        MessageManager mm = new MessageManager(new EfMessageDal());
        MessageValidator messagevalidator = new MessageValidator();
        [Authorize]
        public ActionResult Inbox(string search)
        {
            string p = (string)Session["AdminUserName"];
         
            if (!string.IsNullOrEmpty(search))
            {
                var values = mm.GetListInboxSearch(p, search);
                return View(values);
            }
            else
            {
                var allvalues = mm.GetListInbox(p);
                return View(allvalues);
            }
        }

        public ActionResult Sendbox(string search)
        {

            string p = (string)Session["AdminUserName"];
            
            

            if (!string.IsNullOrEmpty(search))
            {
                var values = mm.GetListSendboxSearch(p,search);
                return View(values);
            }
            else
            {
                var values = mm.GetListSendBox(p);
                return View(values);
            }
            
        }  

        [HttpGet]
        public ActionResult NewMessage()
        {
            return View();
        }
        [HttpPost]
        public ActionResult NewMessage(Message message, string submitType)
        {
            ValidationResult result = messagevalidator.Validate(message);
            if (result.IsValid)
            {
                message.MessageDate = DateTime.Parse(DateTime.Now.ToString());
                message.Status = true;
                message.TaskStatus = false;

                if (submitType == "task")
                {
                    message.TaskStatus = true;
                }
                else if (submitType == "send")
                {
                    message.TaskStatus = false;
                }


                string p = (string)Session["AdminUserName"];
                message.SenderMail = p; 
                mm.AddMessage(message);
                return RedirectToAction("SendBox");
            }
            else
            { 
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }

            }
           
            return View();
        }

        public ActionResult GetInboxMessageDetails(int id)
        {
            var values = mm.GetByID(id);
            return View(values);
        }

        public ActionResult GetSendMessageDetails(int id)
        {
            var values = mm.GetByID(id);
           
            string p = (string)Session["AdminUserName"];
            var count = mm.GetByCountSenderMessage(p);
            ViewBag.sendermailcount = count;
            return View(values);
        }

        public ActionResult GarbageMessage()
        {
            
            string p=(string)Session["AdminUserName"];
            var garbagemessagevalues = mm.GetListGarbage(p);
            return View(garbagemessagevalues);
        }

        public ActionResult TaskMessage()
        {

            string p = (string)Session["AdminUserName"];
            var taskvalues = mm.GetListByTask(p);

            return View(taskvalues);
        }
       
        public ActionResult DeleteMessage(int id)
        {
            var values = mm.GetByID(id);
            values.Status = false;
            values.TaskStatus = false;
            mm.DeleteMessage(values);
            
            return RedirectToAction("Inbox");

        }
      


    }
}

WriterMvcProject/Views/Message/GetInboxMessageDetails.cshtml
@model EntitiyLayer.Concrete.Message
@{
    ViewBag.Title = "GetInboxMessageDetails";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            @*<div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Compose</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Compose</li>
                    </ol>
                </div>
            </div>*@
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("MessageListMenu","Contact")
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Mesajı Oku</h3>
                            <div class="card-tools">
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>



                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5>Konu: @Html.DisplayFor(x => x.Subject)</h5>
                                <h6>
                                    Mail:@Html.DisplayFor(x => x.SenderMail)
                                    <span class="mailbox-read-time float-right">@DateTime.Parse(Html.DisplayFor(x => x.MessageDate).ToString()).ToString("dd-MMMMM-yyyy")</span>
                                    
                                </h6>
                            </div>

                            <!-- /.mailbox-read-info -->
                            
                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message">
                                <p>@Html.DisplayFor(x => x.MessageContent)</p>

                            </div>
                            <!-- /.mailbox-read-message -->
                        </div>
                        <!-- /.card-footer -->

                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
          
            </div><!-- /.row -->
    </section>
</body>
</html>


<script src="~/Templates/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>

WriterMvcProject/Views/Message/Inbox.cshtml
@using EntitiyLayer.Concrete
@model  List<Message>

@{
    ViewBag.Title = "Sendbox";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesaj Sayfası</h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            @Html.Action("MessageListMenu", "Contact")
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Gönderilen Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                @using (Html.BeginForm("Inbox", "Message", FormMethod.Post))
                                {
                                    <p>
                                       @Html.TextBox("search")
                                        <input type="submit" value="Ara" />
                                    </p>
                                }
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            @*<button type="button" class="btn btn-default btn-sm checkbox-toggle">
                    <i class="far fa-square"></i>
                </button>*@
                            <div class="btn-group">
                                @*<button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>*@
                            </div>
                            <!-- /.btn-group -->
                            <a href="/Message/Inbox/" class="btn btn-default btn-sm">
                                <i class="fas fa-sync-alt"></i> Yenile
                            </a>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {


                                        <tr>
                                            <td type="button">
                                                <a href="/Message/DeleteMessage/@item.MessageID">
                                                    <i class="far fa-trash-alt"></i>
                                                </a>
                                            </td>
                                            <td class="mailbox-star"><a href="/Message/GetSendMessageDetails/@item.MessageID"><i class="fas fa-star text-warning"></i></a></td>
                                            <td class="mailbox-name"><a href="/Message/GetSendMessageDetails/@item.MessageID">@item.ReceiverMail</a></td>
                                            <td class="mailbox-subject">
                                                <b>@item.Subject</b> @item.MessageContent.Substring(0, 30)...
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date">@item.MessageDate.ToString("dd-MMMM-yyyy")</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            @*<button type="button" class="btn btn-default btn-sm checkbox-toggle">
                    <i class="far fa-square"></i>
                </button>*@
                            <div class="btn-group">
                                @*<button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>*@
                            </div>
                            <!-- /.btn-group -->
                            @*<button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>*@
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

</body>
</html>

@*<script src="~/Templates/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>*@

WriterMvcProject/Views/Message/NewMessage.cshtml
@model EntitiyLayer.Concrete.Message
@{
    ViewBag.Title = "NewMessage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <link rel="stylesheet" href="~/Templates/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <script src="~/Templates/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Yeni Mesaj Sayfası</h1>
                </div>
                
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("MessageListMenu", "Contact")
                <!-- /.col -->
                <div class="col-md-9">
                    @******* başlangıç******@

                    @using (Html.BeginForm("NewMessage", "Message", FormMethod.Post))
                    {
                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h3 class="card-title">Yeni Mesaj Oluştur</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.Label("Alıcı Adı")
                                    @Html.TextBoxFor(x => x.ReceiverMail, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.ReceiverMail)

                                </div>
                                <div class="form-group">
                                    @Html.Label("Konu")
                                    @Html.TextBoxFor(x => x.Subject, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Subject)
                                </div>
                                <div class="form-group">
                                    @Html.Label("Mesaj")
                                    <textarea @*id="compose-textarea"*@ class="form-control" name="MessageContent" style="height: 300px">
                                
                    </textarea>
                                </div>
                                <div class="form-group">
                                    <div class="btn btn-default btn-file">
                                        <i class="fas fa-paperclip"></i> Dosya Ekle
                                        <input type="file" name="attachment">
                                    </div>
                                    <p class="help-block">Max. 32MB</p>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <div class="float-right">
                                   
                                    
                                        <!-- Form içeriği -->
                                        <button type="submit" class="btn btn-default" name="submitType" value="task"><i class="fas fa-pencil-alt"></i> Taslaklara Kaydet</button>
                                    
                                         <button type="submit" class="btn btn-primary" name="submitType" value="send"><i class="far fa-envelope"></i> Gönder</button>


                                </div>
                                <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
                            </div>
                            <!-- /.card-footer -->
                        </div>
                    }

                    @******* bi******@
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->
    <!--<script src="~/Templates/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>-->
    <!-- Bootstrap 4 -->
    <!--<script src="~/Templates/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>-->
    <!-- AdminLTE App -->
    <!--<script src="~/Templates/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>-->
    <!-- AdminLTE for demo purposes -->
    <!--<script src="~/Templates/AdminLTE-3.0.4/dist/js/demo.js"></script>-->
    <!-- Summernote -->
    <!--<script src="~/Templates/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>-->
    <!-- Page Script -->
    <script>
        $(function () {
            //Add text editor
            $('#compose-textarea').summernote()
        })</script>
</body>
</html>

WriterMvcProject/Views/Message/Sendbox.cshtml
@using EntitiyLayer.Concrete
@model  List<Message>

@{
    ViewBag.Title = "Sendbox";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesaj Sayfası</h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            @Html.Action("MessageListMenu", "Contact")
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Gönderilen Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                @using (Html.BeginForm("SendBox", "Message", FormMethod.Post))
                                {
                                    <p>
                                        @Html.TextBox("search")
                                        <input type="submit" value="Ara" />
                                    </p>
                                }
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            @*<button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                    <i class="far fa-square"></i>
                                </button>*@
                            <div class="btn-group">
                                @*<button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>*@
                            </div>
                            <!-- /.btn-group -->
                            <a href="/Message/Inbox/" class="btn btn-default btn-sm">
                                <i class="fas fa-sync-alt"></i> Yenile
                            </a>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {


                                        <tr>
                                            <td type="button">
                                                <a href="/Message/DeleteMessage/@item.MessageID">
                                                    <i class="far fa-trash-alt"></i>
                                                </a>
                                            </td>
                                            <td class="mailbox-star"><a href="/Message/GetSendMessageDetails/@item.MessageID"><i class="fas fa-star text-warning"></i></a></td>
                                            <td class="mailbox-name"><a href="/Message/GetSendMessageDetails/@item.MessageID">@item.ReceiverMail</a></td>
                                            <td class="mailbox-subject">
                                                <b>@item.Subject</b> @item.MessageContent.Substring(0, 30)...
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date">@item.MessageDate.ToString("dd-MMMM-yyyy")</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            @*<button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                    <i class="far fa-square"></i>
                                </button>*@
                            <div class="btn-group">
                                @*<button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>*@
                            </div>
                            <!-- /.btn-group -->
                            @*<button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>*@
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

</body>
</html>

@*<script src="~/Templates/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>*@